/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nayragames_nativeapi_NativeAPI */

#ifndef _Included_com_nayragames_nativeapi_NativeAPI
#define _Included_com_nayragames_nativeapi_NativeAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nayragames_nativeapi_NativeAPI
 * Method:    ApiVersion
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_nayragames_nativeapi_NativeAPI_ApiVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_nayragames_nativeapi_NativeAPI
 * Method:    ApiName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nayragames_nativeapi_NativeAPI_ApiName
  (JNIEnv *, jclass);

/*
 * Class:     com_nayragames_nativeapi_NativeAPI
 * Method:    authorName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nayragames_nativeapi_NativeAPI_authorName
  (JNIEnv *, jclass);

/*
 * Class:     com_nayragames_nativeapi_NativeAPI
 * Method:    xyz
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nayragames_nativeapi_NativeAPI_xyz
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
